import { Player, PositionZone, PositionSpecific } from '@/types'

// Datos de prueba para posiciones
export const mockPositionZones: PositionZone[] = [
  {
    id: 1,
    abbreviation: 'POR',
    name_es: 'Portero',
    name_en: 'Goalkeeper',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 2,
    abbreviation: 'DEF',
    name_es: 'Defensa',
    name_en: 'Defender',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 3,
    abbreviation: 'MED',
    name_es: 'Mediocampista',
    name_en: 'Midfielder',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 4,
    abbreviation: 'DEL',
    name_es: 'Delantero',
    name_en: 'Forward',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z'
  }
]

export const mockPositionSpecifics: PositionSpecific[] = [
  {
    id: 1,
    abbreviation: 'LD',
    name_es: 'Lateral Derecho',
    name_en: 'Right Back',
    zone_id: 2,
    description_es: 'Defensa que juega por la banda derecha',
    description_en: 'Defender who plays on the right wing',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[1]
  },
  {
    id: 2,
    abbreviation: 'LI',
    name_es: 'Lateral Izquierdo',
    name_en: 'Left Back',
    zone_id: 2,
    description_es: 'Defensa que juega por la banda izquierda',
    description_en: 'Defender who plays on the left wing',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[1]
  },
  {
    id: 3,
    abbreviation: 'DFC',
    name_es: 'Defensa Central',
    name_en: 'Center Back',
    zone_id: 2,
    description_es: 'Defensa que juega en el centro de la defensa',
    description_en: 'Defender who plays in the center of defense',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[1]
  },
  {
    id: 4,
    abbreviation: 'MCD',
    name_es: 'Mediocentro Defensivo',
    name_en: 'Defensive Midfielder',
    zone_id: 3,
    description_es: 'Mediocampista que se enfoca en la recuperación',
    description_en: 'Midfielder focused on ball recovery',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[2]
  },
  {
    id: 5,
    abbreviation: 'MC',
    name_es: 'Mediocentro',
    name_en: 'Center Midfielder',
    zone_id: 3,
    description_es: 'Mediocampista que juega en el centro del campo',
    description_en: 'Midfielder who plays in the center of the field',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[2]
  },
  {
    id: 6,
    abbreviation: 'MCO',
    name_es: 'Mediocentro Ofensivo',
    name_en: 'Attacking Midfielder',
    zone_id: 3,
    description_es: 'Mediocampista que se enfoca en el ataque',
    description_en: 'Midfielder focused on attacking',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[2]
  },
  {
    id: 7,
    abbreviation: 'DC',
    name_es: 'Delantero Centro',
    name_en: 'Center Forward',
    zone_id: 4,
    description_es: 'Delantero que juega en el centro del ataque',
    description_en: 'Forward who plays in the center of attack',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[3]
  },
  {
    id: 8,
    abbreviation: 'SD',
    name_es: 'Segundo Delantero',
    name_en: 'Second Striker',
    zone_id: 4,
    description_es: 'Delantero que juega detrás del delantero centro',
    description_en: 'Forward who plays behind the center forward',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    zone: mockPositionZones[3]
  }
]

// Datos de prueba para jugadores
export const mockPlayers: Player[] = [
  {
    id: 1,
    user_id: 1,
    team_id: 1,
    position_zone_id: 1,
    position_specific_id: undefined,
    name: 'Palito\'s',
    email: 'palitos@example.com',
    phone: '+56912345678',
    date_of_birth: '1990-01-15',
    nationality: 'Chilena',
    jersey_number: 1,
    height: 185,
    weight: 80,
    skill_level: 5,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[0],
    position_specific: undefined,
    team: undefined,
    user: undefined
  },
  {
    id: 2,
    user_id: 2,
    team_id: 1,
    position_zone_id: 2,
    position_specific_id: 1,
    name: 'NachoToro',
    email: 'nachotoro@example.com',
    phone: '+56912345679',
    date_of_birth: '1992-03-20',
    nationality: 'Chilena',
    jersey_number: 11,
    height: 175,
    weight: 70,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[1],
    position_specific: mockPositionSpecifics[0],
    team: undefined,
    user: undefined
  },
  {
    id: 3,
    user_id: 3,
    team_id: 1,
    position_zone_id: 2,
    position_specific_id: 2,
    name: 'Nico Payo',
    email: 'nicopayo@example.com',
    phone: '+56912345680',
    date_of_birth: '1991-07-10',
    nationality: 'Chilena',
    jersey_number: 4,
    height: 180,
    weight: 75,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[1],
    position_specific: mockPositionSpecifics[1],
    team: undefined,
    user: undefined
  },
  {
    id: 4,
    user_id: 4,
    team_id: 1,
    position_zone_id: 4,
    position_specific_id: 7,
    name: 'Chalo G',
    email: 'chalog@example.com',
    phone: '+56912345681',
    date_of_birth: '1993-11-05',
    nationality: 'Chilena',
    jersey_number: 9,
    height: 178,
    weight: 72,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[3],
    position_specific: mockPositionSpecifics[6],
    team: undefined,
    user: undefined
  },
  {
    id: 5,
    user_id: 5,
    team_id: 1,
    position_zone_id: 4,
    position_specific_id: 8,
    name: 'Asmatiz',
    email: 'asmatiz@example.com',
    phone: '+56912345682',
    date_of_birth: '1994-05-12',
    nationality: 'Chilena',
    jersey_number: 10,
    height: 176,
    weight: 68,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[3],
    position_specific: mockPositionSpecifics[7],
    team: undefined,
    user: undefined
  },
  {
    id: 6,
    user_id: 6,
    team_id: 2,
    position_zone_id: 1,
    position_specific_id: undefined,
    name: 'Danilo Atencio',
    email: 'danilo@example.com',
    phone: '+56912345683',
    date_of_birth: '1989-08-25',
    nationality: 'Chilena',
    jersey_number: 6,
    height: 182,
    weight: 78,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[0],
    position_specific: undefined,
    team: undefined,
    user: undefined
  },
  {
    id: 7,
    user_id: 7,
    team_id: 2,
    position_zone_id: 2,
    position_specific_id: 3,
    name: 'Alex',
    email: 'alex@example.com',
    phone: '+56912345684',
    date_of_birth: '1990-12-03',
    nationality: 'Chilena',
    jersey_number: 2,
    height: 177,
    weight: 73,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[1],
    position_specific: mockPositionSpecifics[2],
    team: undefined,
    user: undefined
  },
  {
    id: 8,
    user_id: 8,
    team_id: 2,
    position_zone_id: 2,
    position_specific_id: 2,
    name: 'Reyse Montana',
    email: 'reyse@example.com',
    phone: '+56912345685',
    date_of_birth: '1991-04-18',
    nationality: 'Chilena',
    jersey_number: 3,
    height: 179,
    weight: 74,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[1],
    position_specific: mockPositionSpecifics[1],
    team: undefined,
    user: undefined
  },
  {
    id: 9,
    user_id: 9,
    team_id: 2,
    position_zone_id: 4,
    position_specific_id: 7,
    name: 'Diego',
    email: 'diego@example.com',
    phone: '+56912345686',
    date_of_birth: '1992-09-30',
    nationality: 'Chilena',
    jersey_number: 7,
    height: 175,
    weight: 70,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[3],
    position_specific: mockPositionSpecifics[6],
    team: undefined,
    user: undefined
  },
  {
    id: 10,
    user_id: 10,
    team_id: 2,
    position_zone_id: 4,
    position_specific_id: 8,
    name: 'Chask',
    email: 'chask@example.com',
    phone: '+56912345687',
    date_of_birth: '1993-06-14',
    nationality: 'Chilena',
    jersey_number: 8,
    height: 174,
    weight: 69,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[3],
    position_specific: mockPositionSpecifics[7],
    team: undefined,
    user: undefined
  },
  {
    id: 11,
    user_id: 11,
    team_id: 1,
    position_zone_id: 3,
    position_specific_id: 4,
    name: 'Carlos M',
    email: 'carlos@example.com',
    phone: '+56912345688',
    date_of_birth: '1991-02-22',
    nationality: 'Chilena',
    jersey_number: 5,
    height: 176,
    weight: 71,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[2],
    position_specific: mockPositionSpecifics[3],
    team: undefined,
    user: undefined
  },
  {
    id: 12,
    user_id: 12,
    team_id: 2,
    position_zone_id: 3,
    position_specific_id: 5,
    name: 'Pedro S',
    email: 'pedro@example.com',
    phone: '+56912345689',
    date_of_birth: '1990-10-08',
    nationality: 'Chilena',
    jersey_number: 6,
    height: 178,
    weight: 72,
    skill_level: 4,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[2],
    position_specific: mockPositionSpecifics[4],
    team: undefined,
    user: undefined
  },
  {
    id: 13,
    user_id: 13,
    team_id: 1,
    position_zone_id: 3,
    position_specific_id: 6,
    name: 'Luis R',
    email: 'luis@example.com',
    phone: '+56912345690',
    date_of_birth: '1992-01-15',
    nationality: 'Chilena',
    jersey_number: 8,
    height: 177,
    weight: 73,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[2],
    position_specific: mockPositionSpecifics[5],
    team: undefined,
    user: undefined
  },
  {
    id: 14,
    user_id: 14,
    team_id: 2,
    position_zone_id: 3,
    position_specific_id: 6,
    name: 'Miguel A',
    email: 'miguel@example.com',
    phone: '+56912345691',
    date_of_birth: '1993-03-28',
    nationality: 'Chilena',
    jersey_number: 10,
    height: 175,
    weight: 70,
    skill_level: 3,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    position_zone: mockPositionZones[2],
    position_specific: mockPositionSpecifics[5],
    team: undefined,
    user: undefined
  }
] 